library(shiny)
library(shinydashboard)
library(shinydashboardPlus)
library(dashboardthemes)
library(fontawesome)
library(shinycssloaders)
library(shinyWidgets)
library(shinymeta)
library(DT)
library(tidyverse)
library(cBioPortalData)
library(operator.tools)
library(survival)
library(survminer)

if (!requireNamespace("reshape2", quietly = TRUE))
    BiocManager::install("reshape2")
library(reshape2)

library(RColorBrewer)
